version: '3.8'

services:
    # MySQL Database
    news-db:
        image: mysql:latest
        container_name: news_db
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: news_aggregator_api
            DB_CONNECTION: mysql
            DB_HOST: news-db
            DB_PORT: 3307
            DB_DATABASE: news_aggregator_api
            DB_USERNAME: root
            DB_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3307:3306"
        volumes:
            - news-db-data:/var/lib/mysql
        networks:
            - app-network
        healthcheck:
            test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
            interval: 30s
            timeout: 10s
            retries: 3

    # phpMyAdmin for Database Management
    news-phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: news_phpmyadmin
        restart: unless-stopped
        environment:
            PMA_HOST: news-db
        ports:
            - "8080:80"
        networks:
            - app-network

    # News Aggregator Application
    news-aggregator-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: news_app
        restart: unless-stopped
        volumes:
            - .:/var/www
            - ./docker-resources/utils/php.ini/php.ini:/usr/local/etc/php/php.ini:ro
        depends_on:
            news-db:
                condition: service_healthy
        networks:
            - app-network
        ports:
            - "9000:9000"
        healthcheck:
            test: [ "CMD", "curl", "-f", "http://localhost:9000" ]
            interval: 30s
            timeout: 10s
            retries: 3

    # Nginx Web Server
    nginx:
        image: nginx:latest
        container_name: nginx_server
        restart: unless-stopped
        ports:
            - "9001:80"
        volumes:
            - ./docker-resources/utils/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www
        depends_on:
            - news-aggregator-app
        networks:
            - app-network

volumes:
    news-db-data:

networks:
    app-network:
        driver: bridge
