version: '3.8'

services:
  news-db:
    image: mysql:latest
    container_name: news_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: news_aggregator_api
    ports:
      - "3307:3306"
    volumes:
      - news-db-data:/var/lib/mysql
    networks:
      - app-network

  news-phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: news_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: news-db
    ports:
      - "8080:80"
    networks:
      - app-network

volumes:
  news-db-data:

networks:
  app-network:
    driver: bridge
