version: '3.8'

services:
    news-aggregator-app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: news_app
        volumes:
            - .:/var/www
            - ./docker-resources/utils/php.ini/php.ini:/usr/local/etc/php/php.ini:ro
        depends_on:
            - news-db
        networks:
            - app-network

    nginx:
        image: nginx:latest
        container_name: nginx_server
        ports:
            - "9001:80"
        volumes:
            - ./docker-resources/utils/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:ro
            - .:/var/www
        depends_on:
            - news-aggregator-app
        networks:
            - app-network

volumes:
    news-db-data:

networks:
    app-network:
        external: true
